Nav bar test
makersacademy/example-story-website pull request #19
Opened 2020-09-03 15:45 UTC by mattfreeman-london

All tests are currently passing so submitting branch for review.

2020-09-03 16:01 UTC, Gina-Frankel commented on src/components/navBarItem/navBarItem.tsx
> +export const NavBarItem = (props: any) => {
Can we replace any with something more specific?

2020-09-03 16:01 UTC, Gina-Frankel commented on src/components/navBar/navBar.spec.tsx
> +})
Add a new line at end of file

2020-09-03 16:02 UTC, Gina-Frankel commented on src/components/bookFrontCover/bookFrontCover.spec.tsx
>  })
👍

2020-09-03 16:03 UTC, Gina-Frankel commented on src/components/layout/index.spec.tsx
> +    <Layout >
👍

2020-09-03 16:04 UTC, Gina-Frankel commented on src/content/chapters.md
> +---
What is this file for?

2020-09-04 08:53 UTC, benfurber requested changes
Why was just a big yarn.lock change required?

2020-09-04 08:53 UTC, benfurber commented on src/content/chapters.md
> +---
Same question.

2020-09-04 10:11 UTC, mattfreeman-london commented on src/content/chapters.md
> +---
I have no idea - wasn't aware that it had changed at all. Can take it out again.

2020-09-04 10:14 UTC, mattfreeman-london commented on src/components/navBarItem/navBarItem.tsx
> +export const NavBarItem = (props: any) => {
Sure - can you suggest what? I don't understand props well enough to know what should be swapped in.

2020-09-18 16:56 UTC, closed without merging