Book section merge
makersacademy/example-story-website pull request #20
Opened 2020-09-03 15:58 UTC by Gina-Frankel

**Create a grid with bootstrap on the _DoublePage_ component**

row 1: title taking up 6/12 columns 
row 2: **two BookSection components** each component takes up 6/12 columns
row 3: **two BookSection components** each component takes up 6/12 columns

- Responsive for medium and large screens

![image](https://user-images.githubusercontent.com/60652902/92137718-6251da00-ee05-11ea-94e3-e64821a1da54.png)

**BookSection components**
- If a prop called **line** has been passed down renders a border on the right side of the div
- Renders a box with: 
   -  background colour (at the moment coloured with the same colour as the book)
  -  border 
  - padding

**Other changes** 
- Move background-color to index sass from doublePage sass

2020-09-03 16:58 UTC, cjm106 reviewed
I think we should merge this.

2020-09-03 16:58 UTC, cjm106 commented on src/components/chapterPages/chapterPages.tsx
> -}
I'm not sure we ever got the name right but still think we need this (or a version of ) to help reduce the complexity of the doublePage.tsx component.

2020-09-03 16:58 UTC, cjm106 commented on src/components/doublePage/doublePage.tsx
> +          <BookSection />
Great to get the postioning right!

2020-09-03 16:58 UTC, cjm106 commented on src/components/doublePage/doublePage.tsx
> +          <BookSection />
The code is quite repetitive - should the row be a component in its own right?

2020-09-04 09:00 UTC, benfurber requested changes

2020-09-04 09:00 UTC, benfurber commented on src/components/bookSection/bookSection.tsx
> +    <div className="  px-3 py-2">
What's this spacing in the className doing here!?

2020-09-04 09:00 UTC, benfurber commented on src/components/bookSection/bookSection.tsx
> +export const BookSection = props => {
Are there any props?

2020-09-04 09:00 UTC, benfurber commented on src/components/doublePage/doublePage.scss
> +  border-right: 1px solid black;
Let's have a global definition of black please.

2020-09-04 09:00 UTC, benfurber commented on src/components/doublePage/doublePage.tsx
> +  let customStyleRule = { "border-right": "1px solid black" }
Doesn't look like this is used anywhere?

2020-09-04 09:00 UTC, benfurber commented on src/styles/variables.scss
> +$box-border-colour: #111;
So it's not worth having a global style if the variable is so specific. Why is the box-border this hex?

2020-09-04 09:00 UTC, benfurber commented on src/components/layout/index.scss
> +  background-color: #bcc2c9;
This should be a variable.

2020-09-04 10:40 UTC, Gina-Frankel commented on src/components/doublePage/doublePage.tsx
> +          <BookSection />
Yes agreed - it is very repetitive ... 
We could break the components into a **row** or maybe...

```
 <div className="row">
          <BookSection />
          <BookSection />
</div>
 <div className="row">
          <BookSection />
          <BookSection />
</div>
   
```
`<BookSection />` - would then contain `<div className=" col-md-6 col-lg-6 book-mid-line ">` combined with what it already contains ....

2020-09-04 10:44 UTC, Gina-Frankel commented on src/styles/variables.scss
> +$box-border-colour: #111;
I think that many of our variables names are too specific like 
```
$book-page-color: #ffffff;
$book-cover-color: #ffffff;
```
I am thinking that it maybe should be like: 
$primary-color:
$secondary-color: 

I will have a look at all the names and think about better ways to name them ...

2020-09-04 10:58 UTC, benfurber commented on src/styles/variables.scss
> +$box-border-colour: #111;
Great! That suggestion is a big improvement.

2020-09-04 17:26 UTC, merged