Links
makersacademy/example-story-website pull request #21
Opened 2020-09-03 16:05 UTC by cjm106

The following has been enabled in this branch:
* The creation of chapter pages based on the markdown files  in the contents folder  (the files have the same name as chapter labels to ensure the links work).
* The generation of navbar links based on current chapter labels - next step is to generate links using markdown.

2020-09-03 16:07 UTC, Gina-Frankel commented on gatsby-node.js
> +// }
Delete comments

2020-09-03 16:08 UTC, Gina-Frankel commented on src/templates/chapter.js
> +`
👍

2020-09-03 16:09 UTC, Gina-Frankel commented on src/components/navBarItem/navBarItem.tsx
> +    </a>
`props.chapter could be deconstructed `

2020-09-03 16:18 UTC, cjm106 commented on gatsby-node.js
> +// }
removed

2020-09-03 16:26 UTC, cjm106 commented on src/templates/chapter.js
> +`
It looks to be the preferred option - https://www.gatsbyjs.com/tutorial/part-seven/

2020-09-04 10:53 UTC, benfurber requested changes

2020-09-04 10:53 UTC, benfurber commented on gatsby-node.js
> +exports.onCreateNode = ({ node, getNode, actions }) => {
For readability let's get a gap between these two lines please.

2020-09-04 10:53 UTC, benfurber commented on gatsby-node.js
> +    })
Thoughts on doing?:
```
    const basePath: "pages"

    const slug = createFilePath({ node, getNode, basePath })
    const [name, value] = slug

    createNodeField({ node, name, value })
```

2020-09-04 10:53 UTC, benfurber commented on gatsby-node.js
> +exports.createPages = async ({ graphql, actions }) => {
Let's get a gap between these lines please.

2020-09-04 10:53 UTC, benfurber commented on gatsby-node.js
> +        slug: node.fields.slug,
You're calling `node.fields.slug` twice. How can you dry this up?

2020-09-04 10:53 UTC, benfurber commented on gatsby-node.js
> +      component: path.resolve(`./src/templates/chapter.js`),
With `path.resolve(`./src/templates/chapter.js`)` on this line you're doing more than I'd like on the line. Any thoughts on a different way of doing this?

2020-09-04 10:53 UTC, benfurber commented on src/components/navBarItem/navBarItem.tsx
> +export const NavBarItem = props => {
conscious decision to not add a type def here?

2020-09-04 10:53 UTC, benfurber commented on src/templates/chapter.js
> +export default function NewChapter({ data }) {
Conscious decision to not add a type def here?

2020-09-04 10:53 UTC, benfurber commented on src/templates/chapter.js
> +import { Layout } from "../components"
Line break for readability please. I like to seperate out external imports, from project imports.

2020-09-04 10:53 UTC, benfurber commented on src/templates/chapter.js
> +          <div dangerouslySetInnerHTML={{ __html: post.html }} />
Have you researched other ways than to do a dangerous html call here?

2020-09-04 10:53 UTC, benfurber commented on src/templates/chapter.js
> +  const post = data.markdownRemark
I'd prefer:
```
   const { post } = data.markdownRemark
```

Though you can actually go one step further (then change the implimentation further on):
```
   const { frontmatter, html } = data.markdownRemark.post
   const { title } = frontmatter
```

2020-09-04 10:53 UTC, benfurber commented on src/templates/chapter.js
> +`
We're starting to collect a few graphql queries now, we might want to centralise them soon. Not neccessarily now.

2020-09-04 11:17 UTC, cjm106 commented on gatsby-node.js
> +exports.onCreateNode = ({ node, getNode, actions }) => {
line break added

2020-09-04 11:17 UTC, cjm106 commented on gatsby-node.js
> +exports.createPages = async ({ graphql, actions }) => {
done

2020-09-04 11:48 UTC, cjm106 commented on gatsby-node.js
> +    })
I'm unable to get your suggested chanegs to work - even a partial i.e.    
const [name, value] = slug
    createNodeField({
      node,
      name,
      value,
    })

2020-09-04 11:55 UTC, cjm106 commented on gatsby-node.js
> +        slug: node.fields.slug,
result.data.allMarkdownRemark.edges.forEach(({ node }) => {
    const field = node.fields.slug
    createPage({
      path: field,
      component: path.resolve(`./src/templates/chapter.js`),
      context: {
        slug: field,
      },
    })
  })

2020-09-04 12:10 UTC, cjm106 commented on gatsby-node.js
> +      component: path.resolve(`./src/templates/chapter.js`),
The gatsby-node file is based on the example provided here https://www.gatsbyjs.com/tutorial/part-seven/ - I will need to research this further.  

Are you suggesting something like: 

import MyComponent from 'components/MyComponent
...
component: MyComponent

2020-09-04 12:10 UTC, cjm106 commented on src/templates/chapter.js
> +import { Layout } from "../components"
added

2020-09-04 12:17 UTC, cjm106 commented on src/components/navBarItem/navBarItem.tsx
> +export const NavBarItem = props => {
Yes, I didnt want to do something that might duplicate/conflict with @mattfreeman-london's navBarTest branch

2020-09-04 12:35 UTC, cjm106 commented on src/templates/chapter.js
> +          <div dangerouslySetInnerHTML={{ __html: post.html }} />
Not at this stage, current implementation is based on gatsbyjs.com documentation/tutorial. Would you prefer something similar to this?
var test = React.createClass({
  componentDidUpdate: function(prevProp, prevState){
    this.refs.test.innerHTML = "Hello";
  },
  render: function(){
    return (
      <div contentEditable='true' ref='test'></div>
    );
  }
});

2020-09-04 13:36 UTC, cjm106 commented on src/templates/chapter.js
> +  const post = data.markdownRemark
Both options appear to break things at this stage, producing :

'TypeError: Cannot read property 'frontmatter' of undefined'

2020-09-04 13:37 UTC, cjm106 commented on src/templates/chapter.js
> +`
Will add it to the project board.

2020-09-04 13:52 UTC, cjm106 commented on src/templates/chapter.js
> +export default function NewChapter({ data }) {
Yes. I've converted the file to .tsx  and have defined data as follows
interface Props {
  data: object
}
Is this the correct way to define the typ def?

2020-09-04 15:52 UTC, Gina-Frankel commented on src/templates/chapter.js
> +  const post = data.markdownRemark
I think this may be because there is no property of **post** in data

2020-09-04 15:53 UTC, Gina-Frankel commented on src/templates/chapter.js
> +  const post = data.markdownRemark
![image](https://user-images.githubusercontent.com/60652902/92259476-1d927580-eecf-11ea-8d0d-20d44c19d941.png)

2020-09-04 15:57 UTC, Gina-Frankel commented on src/templates/chapter.js
> +  const post = data.markdownRemark
solution: 
` const { frontmatter, html } = data.markdownRemark
  const { title } = frontmatter`

2020-09-07 08:48 UTC, benfurber commented on gatsby-node.js
> +    })
Ugh. Sorry, I miss typed. 
```
 const [name, value] = [slug]
```
Should do it. I'm honestly on the fence about it anyway, the syntax is a little weird but I like the consistency then for `createNodeField`.

2020-09-07 08:49 UTC, benfurber commented on gatsby-node.js
> +      component: path.resolve(`./src/templates/chapter.js`),
No, I was thinking:
```js
const component = path.resolve(`./src/templates/chapter.js`)
```

2020-09-07 08:50 UTC, benfurber commented on src/templates/chapter.js
> +export default function NewChapter({ data }) {
Yes, though ideally you'd also define what the object is.

2020-09-07 08:52 UTC, benfurber commented on src/templates/chapter.js
> +          <div dangerouslySetInnerHTML={{ __html: post.html }} />
It's the `dangerouslySetInnerHTML` bit I don't really like - though the data isn't coming from a data source the author doesn't have complete control of.  Basically the reason it's dangerous is that it'll allow ANY html tags so it's vunerable to security attacks.

2020-09-07 14:01 UTC, merged